# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=30, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='end',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ponto de Referência'),
        ),
    ]
