# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170109_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número'),
        ),
    ]
