# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20170109_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.PlanoSaude', verbose_name='Plano de Saúde'),
        ),
    ]
