# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadeMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'verbose_name': 'Especialidade',
            },
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='medico',
        ),
        migrations.AddField(
            model_name='especialidademedico',
            name='descricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Especialidade'),
        ),
        migrations.AddField(
            model_name='especialidademedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
