# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20170126_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidademedico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Especialidade', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidademedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Médico'),
        ),
    ]
