# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data', 'medico', 'paciente'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Consulta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora da Consulta'),
        ),
    ]
