# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20170201_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
