# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20170201_1143'),
        ('servicos', '0004_auto_20170201_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
