# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_chamado_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Autor'),
        ),
    ]
