# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0022_auto_20170225_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
