# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0024_auto_20170225_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='restricao_hospitalar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Restrição Hospitalar'),
        ),
    ]
