# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import servicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0026_auto_20170313_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('logotipo', models.ImageField(blank=True, upload_to=servicos.models.media_path, verbose_name='Logotipo')),
                ('rodape', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rodapé')),
            ],
            options={
                'verbose_name_plural': 'Configurações',
                'verbose_name': 'Configuração',
            },
        ),
    ]
